import sys
import getopt
import shutil
import glob
import os

class EmbedClassGen(object):
    def __init__(self):
        pass
        
    def GenerateEmbedClass(self, xml_path):
        xmls = self.GetXmlsList(xml_path)
        r =  '/* =======================================\n'
        r += ' * ### DO NOT EDIT THIS FILE ###\n'
        r += ' * FILE WAS AUTOGENERATED BY XmlEmbed v 1.1\n'
        r += ' * ======================================= */\n'
        r += 'package\n'
        r += '{\n'
        r += '	public dynamic class XmlEmbed\n'
        r += '	{\n'
        for file in xmls:
            # пути нужно указывать относительно исполнимого SWF, а не относительно XmlEmbed:
            r += ('\t\t[Embed(source="../xml/%s", mimeType="application/octet-stream")]\n') % file
            r += ('\t\tpublic var Embed_%s:Class;\n') % file[:len(file)-len('.xml')]
        r += '\t}\n'
        r += '}\n'
        return r

    def GetXmlsList(self, xml_path):
        files = glob.glob(xml_path + "/*.xml")
        names = [os.path.basename(fname) for fname in files]
        return names

def main(args):
    if len(args) != 2:  # if no arguments:
        # show the help:
        print("XmlEmbed 1.0 for FlashGameEngine");
        print("--------------------------------");
        print("How to use:")
        print("xmlembed.exe --xml_path=./path1/xml/ --result_path=./path2/")
        # --xml_path=./xml/ --result_path=./result/
    else:
        xml_path = ""
        result_path = ""
        for i in range(len(args)):
            if args[i].find("--xml_path=") == 0:
                xml_path = args[i][len("--xml_path="):]
            elif args[i].find("--result_path=") == 0:
                result_path = args[i][len("--result_path="):]
        generator = EmbedClassGen()
        result_class = generator.GenerateEmbedClass(xml_path)
        file = open(result_path + "XmlEmbed.as", 'w')
        file.write(result_class)
        file.flush()
        file.close()
        print("'XmlEmbed.as' was generated.");
    pass



if __name__ == "__main__":
    main(sys.argv[1:])
